import streamlit as st
import requests
from fpdf import FPDF, XPos, YPos
from streamlit_lottie import st_lottie
from datetime import date

# 1. Page Config - Updated to Quotix
st.set_page_config(page_title="Quotix Admin", layout="wide")

# --- CUSTOM CSS (Sticky Sidebar & Form Color) ---
st.markdown("""
    <style>
    /* Left Column ni sticky ga unchutundi */
    @media (min-width: 768px) {
        [data-testid="column"]:nth-child(1) {
            position: fixed;
            width: 30% !important;
            height: 100vh;
            z-index: 1;
        }
        /* Right Column scroll avvadaniki gap isthundi */
        [data-testid="column"]:nth-child(2) {
            margin-left: 35% !important;
            width: 60% !important;
        }
    }
    
    /* FORM COLOR CHANGE - Soft Indigo Tint */
    div[data-testid="stContainer"] {
        background-color: #F8F9FF !important;
        border: 1px solid #E0E7FF !important;
        border-radius: 15px !important;
        padding: 20px !important;
    }
    </style>
    """, unsafe_allow_html=True)

# 2. Lottie Animation Loader
def load_lottieurl(url):
    try:
        r = requests.get(url)
        return r.json() if r.status_code == 200 else None
    except:
        return None

lottie_anim = load_lottieurl("https://assets5.lottiefiles.com/packages/lf20_fcfjwiyb.json")

# 3. PDF Generation Function - Rebranded
def create_pdf(client, project, content):
    pdf = FPDF()
    pdf.add_page()
    
    # Header - Quotix Branding
    pdf.set_font("helvetica", 'B', 18)
    pdf.set_text_color(99, 102, 241) # Indigo color
    pdf.cell(0, 10, "QUOTIX - SMART PROPOSAL", align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(10)
    
    # Project Info
    pdf.set_font("helvetica", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Client: {client}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 10, f"Project: {project}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 10, f"Date: {date.today()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)
    
    # Body Content
    pdf.set_font("helvetica", '', 11)
    clean_text = content.replace("₹", "Rs.").replace("**", "").replace("#", "")
    pdf.multi_cell(0, 8, clean_text)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("helvetica", 'I', 8)
    pdf.cell(0, 10, "Generated by Quotix AI Engine", align='C')
    
    return bytes(pdf.output())

# 4. UI Header - Rebranded with modern look
st.markdown("<h1 style='text-align: center; color: #6366F1;'>⚡ QUOTIX</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #6B7280; font-size: 1.2rem;'>AI-Powered Precision Quotations</p>", unsafe_allow_html=True)

# 5. Layout Split
col1, col2 = st.columns([1, 1.5], gap="large")

# Form Section
with col1:
    with st.container(border=True):
        st.subheader("📋 Draft New Quote")
        c_name = st.text_input("Client Name", placeholder="e.g. AdSpark Digital")
        p_name = st.text_input("Project Title", placeholder="e.g. Q2 Branding Package")
        requirements = st.text_area("Scope of Work", height=150, placeholder="Describe requirements...")
        # Note: Updated to width='stretch' for 2026 compatibility
        submit = st.button("Generate Quote 🚀", width='stretch')

# Preview Section
with col2:
    if submit and requirements:
        with st.spinner("Quotix AI is calculating..."):
            try:
                response = requests.post("http://127.0.0.1:8000/generate", json={"text": requirements})
                
                if response.status_code == 200:
                    result = response.json()
                    if "quote" in result:
                        proposal_text = result["quote"].replace("EventSetu", "Quotix") # Auto-replace names
                        
                        st.success("Draft Ready!")
                        
                        st.markdown(f"""
                            <div style="background-color: #f0f4ff; padding: 25px; border-radius: 12px; border-left: 5px solid #6366F1; color: #1e293b; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
                                {proposal_text.replace("\n", "<br>")}
                            </div>
                        """, unsafe_allow_html=True)
                        
                        st.divider()
                        
                        pdf_bytes = create_pdf(c_name, p_name, proposal_text)
                        st.download_button(
                            label="📥 Download Quotix PDF",
                            data=pdf_bytes,
                            file_name=f"Quotix_{c_name.replace(' ', '_')}.pdf",
                            mime="application/pdf",
                            width='stretch'
                        )
                    else:
                        st.error(f"Error: {result.get('error')}")
                else:
                    st.error("Server Link Broken. Start Backend!")
            except Exception as e:
                st.error(f"System Error: {e}")
    else:
        if lottie_anim:
            st_lottie(lottie_anim, height=350)
        else:
            st.info("Enter client details to begin drafting.")